### ISSUE TITLE
这样设置的话，会有间隙，如何处理呢，

### ISSUE THREAD

**Issue by guoshilun** [qfxl/RoundProgressBar#2]
<com.qfxl.view.RoundProgressBar
        android:id="@+id/rpb_1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="32dp"
        android:padding="10dp"
        app:rpb_centerBackgroundColor="#39aa1a"
        app:layout_constraintEnd_toStartOf="@+id/rpb_4"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:rpb_autoStart="true"
        app:rpb_centerTextSize="14sp"
        app:rpb_drawOutsideWrapper="true"
        app:rpb_outsideWrapperColor="#39aa1a"
        app:rpb_countDownTimeInMillis="10000"
        app:rpb_sweepStrokeColor="@color/colorPrimaryDark"
        app:rpb_sweepStrokeWidth="2dp" /> 
![image](https://user-images.githubusercontent.com/15873471/62338830-75142400-b50c-11e9-9378-e1ea1a0b7b74.png)

**Comment by qfxl** [comment]
> ```
> <com.qfxl.view.RoundProgressBar
>     android:id="@+id/rpb_1"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:layout_marginTop="32dp"
>     android:padding="10dp"
>     app:rpb_centerBackgroundColor="#39aa1a"
>     app:layout_constraintEnd_toStartOf="@+id/rpb_4"
>     app:layout_constraintStart_toStartOf="parent"
>     app:layout_constraintTop_toTopOf="parent"
>     app:rpb_autoStart="true"
>     app:rpb_centerTextSize="14sp"
>     app:rpb_drawOutsideWrapper="true"
>     app:rpb_outsideWrapperColor="#39aa1a"
>     app:rpb_countDownTimeInMillis="10000"
>     app:rpb_sweepStrokeColor="@color/colorPrimaryDark"
>     app:rpb_sweepStrokeWidth="2dp" /> 
> ```
> 
> ![image](https://user-images.githubusercontent.com/15873471/62338830-75142400-b50c-11e9-9378-e1ea1a0b7b74.png)

刚看了一下在绘制背景的时候，半径的计算多算了外弧的弧宽的一半，已经修复了这个问题。
已发布1.1.1
